hydra:
  job:
    chdir: True

seed: 123456
batch_size: 64
max_epochs: 30
lr: 1e-5
inverse_weighted_sampling: False

fast_dev_run: False
dataloader_workers: 7
dataset_dir: ???
mlflow_tracking_uri: ???